adds default client nodes and a client builder
launchbadge/hedera-sdk-rust-archived pull request #22
Opened 2018-12-04 21:46 UTC by QuestofIranon

2018-12-05 16:43 UTC, mehcode requested changes

2018-12-05 16:43 UTC, mehcode commented on src/client.rs
> +    raw_client: Arc<grpc::Client>,
Why the name change from `inner` to `raw_client` ?

2018-12-05 16:43 UTC, mehcode commented on src/client.rs
> +    pub fn builder(address: impl AsRef<str>) -> ClientBuilder {
`ClientBuilder`s are meant to last for a very short time. Storing `&'a str` inside should be fine.

2018-12-05 16:43 UTC, mehcode commented on src/client.rs
> +    pub(crate) fn new(address: &impl AsRef<str>) -> Result<Self, Error> {
`&impl AsRef<str>` is redundant.. I think.

2018-12-05 16:43 UTC, mehcode commented on src/client.rs
> +    pub fn node(&mut self, node: AccountId) -> &mut Self {
This should probably be a consuming builder so you can move memory easily at the end. E.g.. each method should take `mut self` and return `Self`.

2018-12-05 16:43 UTC, mehcode commented on src/client.rs
> +        let mut tx = TransactionCryptoCreate::new(self);
After thinking on this more.. this makes way more sense to do in `Transaction::new`. That gets passed the client. Just make the fields `pub(crate)`.

2018-12-05 19:09 UTC, QuestofIranon commented on src/client.rs
> +    pub(crate) fn new(address: &impl AsRef<str>) -> Result<Self, Error> {
Thus needs to be directly usable from the bridge though, right?

2018-12-05 19:13 UTC, mehcode commented on src/client.rs
> +    pub(crate) fn new(address: &impl AsRef<str>) -> Result<Self, Error> {
But a reference to a `AsRef` seems odd

2018-12-05 20:24 UTC, QuestofIranon commented on src/client.rs
> +    pub(crate) fn new(address: &impl AsRef<str>) -> Result<Self, Error> {
ohh I see what you mean. I didn't notice the unneeded `&`

2018-12-05 20:27 UTC, QuestofIranon commented on src/client.rs
> +    raw_client: Arc<grpc::Client>,
Left over from a previous version of the change.

2018-12-06 00:07 UTC, QuestofIranon commented
Don't merge this yet, I'm going to add the default operator to this branch/ pr

2018-12-06 00:58 UTC, QuestofIranon commented
Yeah don't merge this yet, need to clean up the builder after rebasing and I'll add the default operator with this PR as well.

2018-12-06 07:12 UTC, mehcode commented on src/transaction/transaction.rs
> +    pub fn operator(&mut self, id: AccountId, secret: SecretKey) -> &mut Self {
Operator secret should _not_ be provided via normal builder methods. If operator is changed however we should invalidate the stored secret.

2018-12-06 07:14 UTC, mehcode commented on src/transaction/transaction.rs
> +        if let Some(state) = self.as_builder() {
Just as a heads up. The operator must be the **first** signature. I would insert it to the top of the vec right before send.

And there is some code in sign that checks for the 2nd signature and does some special stuff. If we have an operator signature then it needs to check for the first signature.

2018-12-07 23:53 UTC, mehcode commented on src/transaction/transaction.rs
> +        let id = match client.operator {
`client.operator.map(TransactionId::new)`

2018-12-07 23:54 UTC, mehcode commented on src/transaction/transaction.rs
> +            secret: client.operator_secret.clone(),
This should be behind an Arc

2018-12-07 23:54 UTC, mehcode commented on src/client.rs
> +
Forgot to call `set_operator`

2018-12-07 23:54 UTC, mehcode commented on src/client.rs
> +        let raw_client = Arc::new(grpc::Client::new_plain(
`raw_client` -> `inner` or `client`.

2018-12-08 00:34 UTC, merged